services:

  db:
    image: postgres:17.5-alpine
    restart: no
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: TechFood
    profiles:
      - dev
      - prod
      - db

  adminer:
    image: adminer
    restart: no
    ports:
      - "8080:8080"
    profiles:
      - dev
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
    profiles:
      - prod