apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-food-configmap-v1
  labels:
    app: tech-food-configmap-v1
    component: config
    version: v1
data:
  SPRING_APPLICATION_NAME: "TechFood"
  SERVER_PORT: "8000"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  DATABASE_HOST: "host.minikube.internal"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "TechFood"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5432/TechFood"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
