apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-food-deployment-v1
  labels:
    app: tech-food-deployment-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techfood
  template:
    metadata:
      labels:
        app: techfood
    spec:
      containers:
        - name: techfood
          image: techfood:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tech-food-configmap-v1
            - secretRef:
                name: tech-food-db-secret-v1
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"